################################################################################
#
# merge counts (and annotation) from featureCounts 
#
# Usage
#	Rscript get-expr-table.R allIDs.txt gene_annotation 
#
# Note: the gene annotation can be generated by gtf2annot.pl in QuickIsoSeq package
#
# The output:  
#			1. fc-gene-count.txt
#           2. fc-gene-rpkm.txt
#
# Input
#Geneid  Chr     Start   End     Strand  Length  RC-140808-00004_stranded.sort.bam
#ENSG00000223972.4       chr1;chr1;chr1;chr1     11869;12595;12975;13221 12227;12721;13052;14412 +;+;+;+ 1756    27
#ENSG00000243485.2       chr1;chr1;chr1  29554;30267;30976       30039;30667;31109       +;+;+   1021    0
#ENSG00000237613.2       chr1;chr1;chr1  34554;35245;35721       35174;35481;36081       -;-;-   1219    0
#
# Shanrong Zhao
#
# December 5, 2018
#
################################################################################

args <- commandArgs(trailingOnly = TRUE)
len=length(args)
if ( len < 2) {
	print ("Please input <id file> <gene_annotation_file>\n")
	q(save = "no")
}

manifest.file <- args[1]
annotation.file <- args[2]

if ( ! file.exists(annotation.file)) {
        print ( paste("Annotation file", annotation.file, " does not exist!", sep=" "))
        q(save = "no")
}
anno <- read.table(annotation.file, header=TRUE, sep="\t")

#read all sample id
manifest <- read.table(manifest.file, header=F)
samples <- manifest[,1]

results = list()
i=0
for (id in samples) {
	filename = paste(id, "/", id, ".featureCounts.txt", sep="")
	
	data <- read.table(filename, header=TRUE, stringsAsFactors=F, check.names = F)
	data <- data[with(data, order(Geneid)),]

	results[[id]] = data[,7]
	if ( i < 1 ) {
		genes=data[,1]
		gene_lens=data[,6]
	}
	i <- i+1
}


anno <- cbind(anno, length=gene_lens)
counts= as.data.frame( do.call("cbind", results))
expr.count = cbind(gene=genes, counts )	
merged.count <- merge(anno,expr.count)	
write.table(merged.count, "fc-gene-counts.txt", sep="\t",row.names = F, quote = F)

total=apply(counts,2,sum)
cpm <- t( t(counts)/total*1000000)
fpkm = round( cpm /gene_lens*1000, digits=3)

expr.fpkm = cbind(gene=genes, fpkm )
merged.fpkm <- merge(anno,expr.fpkm)
write.table(merged.fpkm,"fc-gene-rpkm.txt", sep="\t",row.names = F, quote = F)
